import { useCallback, useContext, useEffect, useRef, useState, lazy, Suspense } from "react";
import toast from "react-hot-toast";
import { ChatContext } from "../../context/ChatContext";
import { AuthContext } from "../../context/AuthContext";
import assets from "../assets/assets";
import { formatMessageTime } from "../lib/utils";
import VoiceChatModal from "./VoiceChatModal";

const EmojiStickerPicker = lazy(() => import("./EmojiStickerPicker"));

const imgError = (e) => {
    e.target.src = assets.avatar_icon;
};

const ChatContainer = () => {
    const {
        messages,
        selectedUser,
        selectedGroup,
        setSelectedUser,
        setSelectedGroup,
        sendMessage,
        getMessages,
        addReaction,
        editMessage,
        deleteMessage,
    } = useContext(ChatContext);
    const { authUser, onlineUsers } = useContext(AuthContext);

    const scrollEnd = useRef(null);
    const inputRef = useRef(null);
    const [showMenu, setShowMenu] = useState(null);

    const [input, setInput] = useState("");
    const [isSending, setIsSending] = useState(false);
    const [showPicker, setShowPicker] = useState(false);
    const [editingMessage, setEditingMessage] = useState(null);
    const [showVoiceChat, setShowVoiceChat] = useState(false);

    const reactionEmojis = ["👍", "❤️", "😂", "😮", "😢", "😡"];
    const autoGeneratedMessages = [
        "Hey! How's it going?",
        "What's up?",
        "Nice weather we're having today, huh?",
        "Did you watch any good shows lately?",
        "I had a great day today!",
        "What are your plans for the weekend?",
        "Just wanted to say hi!",
        "Have you eaten yet?",
        "Hope you're having a good day!",
        "Long time no chat!",
        "What's new with you?",
        "I miss our conversations!",
        "How's work/school going?",
        "Have you been up to anything fun?",
        "Wanna grab coffee sometime?",
        "What's your favorite song right now?",
        "I just tried a new recipe, it was amazing!",
        "Did you see that crazy news story?",
        "Happy [day of week]! 🎉",
        "Sending good vibes your way!",
    ];

    const selected = selectedUser || selectedGroup;
    const isGroup = !!selectedGroup;

    useEffect(() => {
        if (selected?._id) getMessages(selected._id);
    }, [selected?._id, getMessages]);

    useEffect(() => {
        scrollEnd.current?.scrollIntoView({ behavior: "smooth" });
    }, [messages]);

    useEffect(() => {
        if (editingMessage) {
            setInput(editingMessage.text);
            inputRef.current?.focus();
        }
    }, [editingMessage]);

    const handleSendMessage = async (e) => {
        e?.preventDefault();
        if (!input.trim() || isSending) return;

        setIsSending(true);
        if (editingMessage) {
            await editMessage(editingMessage.id, input.trim());
            setEditingMessage(null);
        } else {
            await sendMessage({ text: input.trim() });
        }
        setInput("");
        setIsSending(false);
        inputRef.current?.focus();
    };

    const handleSendImage = async (e) => {
        const file = e.target.files[0];
        e.target.value = "";
        if (!file) return;

        if (!file.type.startsWith("image/")) {
            toast.error("Please select a valid image file.");
            return;
        }
        if (file.size > 5 * 1024 * 1024) {
            toast.error("Image must be smaller than 5 MB.");
            return;
        }

        setIsSending(true);
        const reader = new FileReader();
        reader.onloadend = async () => {
            await sendMessage({ image: reader.result });
            setIsSending(false);
        };
        reader.onerror = () => {
            toast.error("Failed to read image.");
            setIsSending(false);
        };
        reader.readAsDataURL(file);
    };

    const handleSendFile = async (e) => {
        const file = e.target.files[0];
        e.target.value = "";
        if (!file) return;

        if (file.size > 10 * 1024 * 1024) {
            toast.error("File must be smaller than 10 MB.");
            return;
        }

        setIsSending(true);
        const reader = new FileReader();
        reader.onloadend = async () => {
            await sendMessage({
                file: {
                    base64: reader.result,
                    name: file.name,
                    type: file.type,
                    size: file.size,
                },
            });
            setIsSending(false);
        };
        reader.onerror = () => {
            toast.error("Failed to read file.");
            setIsSending(false);
        };
        reader.readAsDataURL(file);
    };

    const handleSendLocation = async () => {
        if (!navigator.geolocation) {
            toast.error("Geolocation is not supported by your browser.");
            return;
        }

        setIsSending(true);
        navigator.geolocation.getCurrentPosition(
            async (position) => {
                const { latitude, longitude } = position.coords;
                await sendMessage({
                    location: {
                        latitude,
                        longitude,
                        address: `${latitude.toFixed(4)}, ${longitude.toFixed(4)}`,
                    },
                });
                setIsSending(false);
            },
            (error) => {
                toast.error("Failed to get your location.");
                setIsSending(false);
            }
        );
    };

    const handleEmojiSelect = useCallback((emoji) => {
        setInput((prev) => prev + emoji);
        setShowPicker(false);
        inputRef.current?.focus();
    }, []);

    const handleStickerSelect = useCallback(async (sticker) => {
        setShowPicker(false);
        setIsSending(true);
        await sendMessage({ text: sticker, isSticker: true });
        setIsSending(false);
    }, [sendMessage]);

    const handleReaction = async (messageId, emoji) => {
        await addReaction(messageId, emoji);
        setShowMenu(null);
    };

    const handleDelete = async (messageId) => {
        await deleteMessage(messageId);
        setShowMenu(null);
    };

    const handleEdit = (message) => {
        setEditingMessage({ id: message._id, text: message.text });
        setShowMenu(null);
    };

    const formatFileSize = (bytes) => {
        if (bytes < 1024) return bytes + " B";
        if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + " KB";
        return (bytes / (1024 * 1024)).toFixed(1) + " MB";
    };

    const getReactionCounts = (reactions) => {
        const counts = {};
        reactions?.forEach((r) => {
            counts[r.emoji] = (counts[r.emoji] || 0) + 1;
        });
        return counts;
    };

    const handleAutoGenerate = () => {
        const randomMsg =
            autoGeneratedMessages[Math.floor(Math.random() * autoGeneratedMessages.length)];
        let finalMsg = randomMsg;
        if (finalMsg.includes("[day of week]")) {
            const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
            finalMsg = finalMsg.replace("[day of week]", days[new Date().getDay()]);
        }
        setInput(finalMsg);
        inputRef.current?.focus();
    };

    const isOnline = isGroup ? true : onlineUsers.includes(selectedUser?._id);

    const getSenderName = (msg) => {
        if (!isGroup) return null;
        const member = selectedGroup?.members?.find(
            (m) => (m._id || m).toString() === (msg.senderId._id || msg.senderId).toString()
        );
        return member?.fullName || "Unknown";
    };

    const getAvatar = (msg, isMine) => {
        if (isGroup) {
            const member = selectedGroup?.members?.find(
                (m) => (m._id || m).toString() === (msg.senderId._id || msg.senderId).toString()
            );
            return member?.profilePic || assets.avatar_icon;
        }
        return isMine ? authUser.profilePic || assets.avatar_icon : selectedUser.profilePic || assets.avatar_icon;
    };

    if (!selected) {
        return (
            <div className="flex flex-col items-center justify-center gap-3 bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 max-md:hidden">
                <img src={assets.logo_icon} alt="" className="w-24 opacity-60" />
                <p className="text-xl font-medium text-white/60">Chat anytime, anywhere</p>
            </div>
        );
    }

    return (
        <div className="flex flex-col h-full bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 overflow-hidden">
            <div className="flex items-center gap-4 px-6 py-4 border-b border-white/10 flex-shrink-0">
                <img
                    src={selected.profilePic || selected.avatar || assets.avatar_icon}
                    alt={selected.fullName || selected.name}
                    onError={imgError}
                    className="w-12 h-12 rounded-full object-cover"
                />
                <div className="flex-1 min-w-0">
                    <p className="text-white font-bold text-lg truncate">{selected.fullName || selected.name}</p>
                    {isGroup ? (
                        <p className="text-sm text-gray-400">{selected.members?.length || 0} members</p>
                    ) : (
                        <p className={`text-sm ${isOnline ? "text-green-400" : "text-gray-400"}`}>
                            {isOnline ? "Online" : "Offline"}
                        </p>
                    )}
                </div>
                <button
                    type="button"
                    onClick={() => setShowVoiceChat(true)}
                    className="w-12 h-12 flex items-center justify-center rounded-full bg-white/10 hover:bg-white/20 transition duration-300 transform hover:scale-110"
                    aria-label="Voice Chat"
                >
                    📞
                </button>
                {editingMessage && (
                    <button
                        type="button"
                        onClick={() => setEditingMessage(null)}
                        className="text-sm text-gray-400 hover:text-white font-medium"
                    >
                        Cancel
                    </button>
                )}
                <button
                    type="button"
                    onClick={() => {
                        setSelectedUser(null);
                        setSelectedGroup(null);
                    }}
                    className="md:hidden p-2"
                    aria-label="Back"
                >
                    <img src={assets.arrow_icon} alt="Back" className="w-7" />
                </button>
            </div>

            <div className="flex-1 overflow-y-auto p-6 flex flex-col gap-4">
                {messages.length === 0 && (
                    <p className="text-center text-gray-500 text-base mt-12 select-none">
                        No messages yet. Say hello! 👋
                    </p>
                )}

                {messages.map((msg, index) => {
                    const isMine = (msg.senderId._id || msg.senderId).toString() === authUser._id.toString();

                    const isSticker =
                        msg.isSticker ||
                        (!msg.image && !msg.file?.url && !msg.location && msg.text && [...msg.text].length <= 2 && /^\p{Emoji}/u.test(msg.text));

                    if (msg.deleted) {
                        return (
                            <div
                                key={msg._id || index}
                                className={`flex items-end gap-3 ${isMine ? "flex-row-reverse" : "flex-row"}`}
                            >
                                <p className="text-sm text-gray-500 italic px-4 py-2 bg-white/5 rounded-xl">
                                    Message deleted
                                </p>
                            </div>
                        );
                    }

                    const reactionCounts = getReactionCounts(msg.reactions);
                    const senderName = getSenderName(msg);

                    return (
                        <div
                            key={msg._id || index}
                            className={`flex items-end gap-3 ${
                                isMine ? "flex-row-reverse" : "flex-row"
                            } relative group`}
                        >
                            <div className="flex flex-col items-center gap-1 flex-shrink-0">
                                <img
                                    src={getAvatar(msg, isMine)}
                                    alt=""
                                    onError={imgError}
                                    className="w-10 h-10 rounded-full object-cover"
                                />
                                <span className="text-gray-500 text-xs">{formatMessageTime(msg.createdAt)}</span>
                            </div>

                            <div className="flex flex-col gap-2 max-w-[70%]">
                                {isGroup && !isMine && senderName && (
                                    <p className="text-sm text-purple-300 font-medium ml-2">{senderName}</p>
                                )}

                                {msg.location ? (
                                    <a
                                        href={`https://www.google.com/maps?q=${msg.location.latitude},${msg.location.longitude}`}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className={`px-4 py-3 rounded-2xl text-sm text-white break-words bg-gradient-to-r from-purple-500/20 to-blue-500/20 border border-white/10 ${
                                            isMine ? "rounded-tr-none" : "rounded-tl-none"
                                        } flex items-center gap-3 hover:from-purple-500/30 hover:to-blue-500/30 transition duration-300`}
                                    >
                                        <span className="text-2xl">📍</span>
                                        <span className="truncate font-medium">{msg.location.address}</span>
                                    </a>
                                ) : msg.file?.url ? (
                                    <a
                                        href={msg.file.url}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className={`px-4 py-3 rounded-2xl text-sm text-white break-words bg-gradient-to-r from-purple-500/20 to-blue-500/20 border border-white/10 ${
                                            isMine ? "rounded-tr-none" : "rounded-tl-none"
                                        } flex items-center gap-3 hover:from-purple-500/30 hover:to-blue-500/30 transition duration-300`}
                                    >
                                        <span className="text-2xl">📎</span>
                                        <div className="flex flex-col min-w-0">
                                            <span className="truncate font-medium">{msg.file.name}</span>
                                            <span className="text-xs text-gray-300">{formatFileSize(msg.file.size)}</span>
                                        </div>
                                    </a>
                                ) : msg.image ? (
                                    <img
                                        src={msg.image}
                                        alt="Sent image"
                                        className="max-w-[240px] max-h-[320px] rounded-2xl border border-white/10 cursor-pointer hover:opacity-90 transition duration-300 object-contain"
                                        onClick={() => window.open(msg.image, "_blank")}
                                        loading="lazy"
                                        onError={(e) => {
                                            e.target.style.display = "none";
                                        }}
                                    />
                                ) : isSticker ? (
                                    <div
                                        className={`flex items-center justify-center rounded-3xl p-4 bg-white/5 hover:bg-white/10 transition duration-300 cursor-default select-none ${
                                            isMine ? "rounded-br-none" : "rounded-bl-none"
                                        }`}
                                        title="Sticker"
                                    >
                                        <span className="text-6xl leading-none">{msg.text}</span>
                                    </div>
                                ) : (
                                    <div
                                        className={`px-4 py-3 rounded-2xl text-sm text-white max-w-[280px] break-words bg-gradient-to-r from-purple-500/20 to-blue-500/20 border border-white/10 ${
                                            isMine ? "rounded-tr-none" : "rounded-tl-none"
                                        }`}
                                    >
                                        <p className="font-medium">{msg.text}</p>
                                        {msg.edited && (
                                            <span className="text-[10px] text-gray-400 ml-2">(edited)</span>
                                        )}
                                    </div>
                                )}

                                {Object.keys(reactionCounts).length > 0 && (
                                    <div className="flex gap-2 bg-white/10 rounded-full px-3 py-1.5 self-end">
                                        {Object.entries(reactionCounts).map(([emoji, count]) => (
                                            <button
                                                key={emoji}
                                                onClick={() => handleReaction(msg._id, emoji)}
                                                className="text-base hover:scale-110 transition duration-300"
                                            >
                                                {emoji} {count > 1 ? count : ""}
                                            </button>
                                        ))}
                                    </div>
                                )}
                            </div>

                            <div className="absolute right-0 md:right-auto md:left-0 top-0 md:hidden group-hover:flex flex-col gap-1">
                                <button
                                    onClick={() => setShowMenu(showMenu === msg._id ? null : msg._id)}
                                    className="p-1.5 rounded-full bg-white/10 hover:bg-white/20"
                                >
                                    ⋮
                                </button>
                            </div>
                            <div className="hidden md:flex absolute right-0 md:right-auto md:left-0 top-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                                <div className="flex gap-1 bg-white/10 rounded-full p-1.5">
                                    {reactionEmojis.map((emoji) => (
                                        <button
                                            key={emoji}
                                            onClick={() => handleReaction(msg._id, emoji)}
                                            className="w-7 h-7 flex items-center justify-center rounded-full hover:bg-white/20 transition duration-300"
                                        >
                                            {emoji}
                                        </button>
                                    ))}
                                    {isMine && (
                                        <>
                                            <button
                                                onClick={() => handleEdit(msg)}
                                                className="w-7 h-7 flex items-center justify-center rounded-full hover:bg-white/20 transition duration-300"
                                                title="Edit"
                                            >
                                                ✏️
                                            </button>
                                            <button
                                                onClick={() => handleDelete(msg._id)}
                                                className="w-7 h-7 flex items-center justify-center rounded-full hover:bg-white/20 transition duration-300"
                                                title="Delete"
                                            >
                                                🗑️
                                            </button>
                                        </>
                                    )}
                                </div>
                            </div>

                            {showMenu === msg._id && (
                                <div className="absolute right-2 top-10 z-50 bg-gradient-to-br from-slate-800 to-slate-900 rounded-2xl shadow-2xl p-3 flex flex-col gap-2 md:hidden border border-white/10">
                                    <div className="flex gap-1 border-b border-white/10 pb-2">
                                        {reactionEmojis.map((emoji) => (
                                            <button
                                                key={emoji}
                                                onClick={() => handleReaction(msg._id, emoji)}
                                                className="w-8 h-8 flex items-center justify-center rounded-xl hover:bg-white/10 transition duration-300"
                                            >
                                                {emoji}
                                            </button>
                                        ))}
                                    </div>
                                    {isMine && (
                                        <>
                                            <button
                                                onClick={() => handleEdit(msg)}
                                                className="px-4 py-2 text-left text-sm text-white hover:bg-white/10 rounded-xl transition duration-300"
                                            >
                                                ✏️ Edit
                                            </button>
                                            <button
                                                onClick={() => handleDelete(msg._id)}
                                                className="px-4 py-2 text-left text-sm text-red-400 hover:bg-white/10 rounded-xl transition duration-300"
                                            >
                                                🗑️ Delete
                                            </button>
                                        </>
                                    )}
                                </div>
                            )}
                        </div>
                    );
                })}
                <div ref={scrollEnd} />
            </div>

            <div className="flex-shrink-0 flex items-center gap-3 px-6 py-5 border-t border-white/10 bg-slate-900/50">
                <div className="relative flex-shrink-0 flex gap-2">
                    <button
                        type="button"
                        onClick={handleAutoGenerate}
                        className="w-11 h-11 flex items-center justify-center rounded-full text-xl transition duration-300 hover:bg-white/10 text-gray-400 hover:text-white transform hover:scale-110"
                        aria-label="Auto generate message"
                        title="Auto generate a friendly message"
                    >
                        ✨
                    </button>
                    <button
                        type="button"
                        onClick={handleSendLocation}
                        disabled={isSending}
                        className="w-11 h-11 flex items-center justify-center rounded-full text-xl transition duration-300 hover:bg-white/10 text-gray-400 hover:text-white disabled:opacity-40 transform hover:scale-110"
                        aria-label="Share location"
                        title="Share your location"
                    >
                        📍
                    </button>
                    <button
                        type="button"
                        onClick={() => setShowPicker((v) => !v)}
                        className={`w-11 h-11 flex items-center justify-center rounded-full text-xl transition duration-300 transform hover:scale-110 ${
                            showPicker
                                ? "bg-gradient-to-r from-purple-500/30 to-blue-500/30 text-purple-300"
                                : "hover:bg-white/10 text-gray-400 hover:text-white"
                        }`}
                        aria-label="Emoji & Stickers"
                        title="Emoji & Stickers"
                    >
                        😊
                    </button>

                    {showPicker && (
                        <Suspense
                            fallback={
                                <div className="absolute bottom-full mb-3 left-0 z-50 w-[360px] h-[440px] rounded-3xl bg-gradient-to-br from-slate-900 to-slate-800 border border-white/10 flex items-center justify-center">
                                    <div className="w-10 h-10 rounded-full border-3 border-purple-400 border-t-transparent animate-spin" />
                                </div>
                            }
                        >
                            <EmojiStickerPicker
                                onEmojiSelect={handleEmojiSelect}
                                onStickerSelect={handleStickerSelect}
                                onClose={() => setShowPicker(false)}
                            />
                        </Suspense>
                    )}
                </div>

                <div className="flex-1 flex items-center bg-white/5 border border-white/10 rounded-full px-5 gap-3">
                    <input
                        ref={inputRef}
                        type="text"
                        placeholder={editingMessage ? "Edit message..." : "Type a message..."}
                        value={input}
                        onChange={(e) => setInput(e.target.value)}
                        onKeyDown={(e) => {
                            if (e.key === "Enter" && !e.shiftKey) handleSendMessage(e);
                        }}
                        disabled={isSending}
                        className="flex-1 bg-transparent text-white text-base py-3.5 outline-none placeholder-gray-400 disabled:opacity-50"
                    />

                    <label
                        htmlFor="chat-file"
                        className={`cursor-pointer flex-shrink-0 transition duration-300 ${
                            isSending ? "opacity-40 pointer-events-none" : ""
                        }`}
                        title="Send file"
                    >
                        <span className="text-xl opacity-70 hover:opacity-100 transition duration-300">📎</span>
                    </label>
                    <input
                        id="chat-file"
                        type="file"
                        hidden
                        onChange={handleSendFile}
                    />

                    <label
                        htmlFor="chat-image"
                        className={`cursor-pointer flex-shrink-0 transition duration-300 ${
                            isSending ? "opacity-40 pointer-events-none" : ""
                        }`}
                        title="Send image"
                    >
                        <img
                            src={assets.gallery_icon}
                            alt="Attach image"
                            className="w-6 opacity-70 hover:opacity-100 transition duration-300"
                        />
                    </label>
                    <input
                        id="chat-image"
                        type="file"
                        accept="image/png,image/jpeg,image/gif,image/webp"
                        hidden
                        onChange={handleSendImage}
                    />
                </div>

                <button
                    type="button"
                    onClick={handleSendMessage}
                    disabled={isSending || !input.trim()}
                    className="flex-shrink-0 disabled:opacity-40 transition duration-300 transform hover:scale-110 active:scale-95"
                    aria-label="Send message"
                >
                    {isSending ? (
                        <div className="w-11 h-11 rounded-full border-3 border-purple-400 border-t-transparent animate-spin" />
                    ) : (
                        <img src={assets.send_button} alt="Send" className="w-11" />
                    )}
                </button>
            </div>

            {showVoiceChat && (
                <VoiceChatModal onClose={() => setShowVoiceChat(false)} />
            )}
        </div>
    );
};

export default ChatContainer;
